### ISSUE TITLE
Incorrect page titles

### ISSUE THREAD

**Issue by thomasio101** [stefvanhouten/WebdevPeriod3#19]
It seems like the profile page has an incorrect title, this issue might be occurring in other places as well.

# Example
![image](https://user-images.githubusercontent.com/12574444/109979425-2d183d00-7cff-11eb-8a22-b0a94927ae64.png)
As you can see, the profile page is titled "Privacy Policy".
# Potential solution
Replacing [the following code in `Areas/Identity/Views/Profile/Index.cshtml`](https://github.com/stefvanhouten/WebdevPeriod3/blob/61f260d9c5928148b2f86968878758095ccf2723/WebdevPeriod3/Areas/Identity/Views/Profile/Index.cshtml#L3);
```csharp
ViewData["Title"] = "Privacy Policy";
```
With this;
```csharp
ViewData["Title"] = "Profile";
```
Could solve the issue.

**Comment by stefvanhouten** [comment]
Solved but I will leave this issue open so other people can look at it as an example.
