### ISSUE TITLE
"UserCreated" in profile is not retrieved dynamically from database

### ISSUE THREAD

**Issue by SDanDyS** [stefvanhouten/WebdevPeriod3#21]
"member since" has been overlooked on. It contains a hard-coded value.
The created record (table Users) does not contain a timestamp on which the record was created and therefore we cannot retrieve any data regarding the user being a "member since".

### Solution

Add a column in the database as either "CreatedAt" or "RecordCreated" of type `DateTime`.

Change in [https://github.com/stefvanhouten/WebdevPeriod3/blob/sprint-2/WebdevPeriod3/Areas/Identity/Views/Profile/Index.cshtml](https://github.com/stefvanhouten/WebdevPeriod3/blob/sprint-2/WebdevPeriod3/Areas/Identity/Views/Profile/Index.cshtml) the following line:

Change: `<span class="ml-auto">Nov 07, 2016</span>`
To: `<span class="ml-auto">@Model.UserInformation.CreatedAt</span>`

**Comment by thomasio101** [comment]
Hi Daniel, could you fix the link to the code?

To make it work, you should go to the file (on the `sprint-2` branch) and create a permalink to the line you'd like to point to.

Anyways, shall I make a pull request to resolve this issue?

**Comment by thomasio101** [comment]
@SDanDyS, users don't have a `CreatedAt` property. Shall we remove this field from the profile page?

**Comment by SDanDyS** [comment]
@thomasio101 My knowledge regarding the database setup and the overall code structure is not as much as yours, therefore you may decide whether it's efficient to implement such thing or to drop if from the profile page.

I would also like to point out the fact that a user cannot create an "about yourself", upon closer examination.

If the call is to be made by me: I suggest we drop these features to prevent any unforeseen circumstances in the future.

**Comment by thomasio101** [comment]
That sounds like a good plan. I'll draw up a proposal (in the form of a pull request) to remove some of the extraneous features from the profile page.

**Comment by thomasio101** [comment]
Some of the extraneous features have been removed from the profile page by #22, thus, I'm closing this issue.
